my:
  datasource:
    url: local.db.com
    username: local.user
    password: local_pw
    etc:
      max-connection: 10
      timeout: 60s
      options: LOCAL,CACHE


---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev.user
    password: dev_pw
    etc:
      max-connection: 20
      timeout: 60s
      options: LOCAL,CACHE
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: prod.user
    password: prod_pw
    etc:
      max-connection: 50
      timeout: 60s
      options: LOCAL,CACHE